# Generated by Django 6.0.2 on 2026-02-10 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Constituency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Trippunithura", max_length=200, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, help_text="e.g. TPA", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Constituencies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Booth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(help_text="Booth Number")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name/location of the booth",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "constituency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booths",
                        to="core_db.constituency",
                    ),
                ),
            ],
            options={
                "ordering": ["constituency", "number"],
                "unique_together": {("constituency", "number")},
            },
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                ("epic_id", models.CharField(db_index=True, max_length=50)),
                ("full_name", models.CharField(db_index=True, max_length=300)),
                ("relation_type", models.CharField(blank=True, max_length=50)),
                ("relation_name", models.CharField(blank=True, max_length=300)),
                ("house_no", models.CharField(blank=True, max_length=100)),
                (
                    "house_name",
                    models.CharField(blank=True, db_index=True, max_length=300),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
                (
                    "source_file",
                    models.CharField(help_text="Original PDF Filename", max_length=300),
                ),
                (
                    "original_serial",
                    models.CharField(
                        blank=True, help_text="Raw OCR value if needed", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("FLAGGED", "Flagged for Review"),
                            ("AUTO_HEALED", "Auto-Healed Serials"),
                        ],
                        default="VERIFIED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voters",
                        to="core_db.booth",
                    ),
                ),
            ],
            options={
                "ordering": ["booth", "serial_no"],
                "permissions": [("can_export_data", "Can export voter data to Excel")],
            },
        ),
    ]
