# Generated by Django 6.0.2 on 2026-02-11 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MANAGER", "Bird's Eye View (All Data)"),
                            ("CONSTITUENCY", "Constituency Level Access"),
                            ("BOOTH", "Booth Level Access"),
                        ],
                        default="BOOTH",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_booths",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific booths this user can access (for BOOTH role)",
                        related_name="assigned_users",
                        to="core_db.booth",
                    ),
                ),
                (
                    "assigned_constituencies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Constituencies this user can access (for CONSTITUENCY role)",
                        related_name="assigned_users",
                        to="core_db.constituency",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
