# Generated by Django 6.0.2 on 2026-02-12 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_download",
            field=models.BooleanField(
                default=False, help_text="Can this user export CSV/Excel?"
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="phone_no",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="assigned_booths",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_users", to="core_db.booth"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="assigned_constituencies",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_users", to="core_db.constituency"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERUSER", "Superuser (Global Access)"),
                    ("EMPLOYEE", "Employee (Upload Only)"),
                    ("CONSTITUENCY", "Constituency Level Manager"),
                    ("LOCAL_BODY", "Local Body Level Manager"),
                    ("BOOTH", "Booth Level Worker"),
                ],
                default="BOOTH",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LocalBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("PANCHAYAT", "Panchayath"),
                            ("MUNICIPALITY", "Municipality"),
                            ("CORPORATION", "Corporation"),
                        ],
                        default="PANCHAYAT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "constituency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_bodies",
                        to="core_db.constituency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Local Bodies",
                "ordering": ["name"],
                "unique_together": {("constituency", "name", "body_type")},
            },
        ),
        migrations.AddField(
            model_name="booth",
            name="local_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booths",
                to="core_db.localbody",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="assigned_local_bodies",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_users", to="core_db.localbody"
            ),
        ),
    ]
