# Generated by Django 6.0.2 on 2026-02-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0003_userprofile_can_download_voter_phone_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="polling_station_name",
            field=models.CharField(
                blank=True,
                help_text="Physical location of the polling station",
                max_length=500,
            ),
        ),
    ]
