# Generated by Django 6.0.1 on 2026-02-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0005_voter_current_location_voter_voter_leaning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="current_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOCAL", "Local"),
                    ("ABROAD", "Abroad"),
                    ("STATE", "Another State"),
                    ("DISTRICT", "Another District"),
                ],
                db_index=True,
                default="LOCAL",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="voter_leaning",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUPPORTER", "Supporter"),
                    ("NEUTRAL", "Neutral"),
                    ("OPPONENT", "Opponent"),
                ],
                db_index=True,
                default="NEUTRAL",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="voting_probability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONFIRMED", "Confirmed"),
                    ("LIKELY", "Likely"),
                    ("UNLIKELY", "Unlikely"),
                    ("OUT_OF_STATION", "Out of Station"),
                ],
                db_index=True,
                default="LIKELY",
                max_length=20,
                null=True,
            ),
        ),
    ]
