# Generated by Django 6.0.1 on 2026-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0007_alter_voter_current_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="polling_station_no",
            field=models.CharField(
                blank=True,
                help_text="Polling Station Number (if different from booth number)",
                max_length=100,
            ),
        ),
    ]
