# Generated by Django 6.0.1 on 2026-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0008_booth_polling_station_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="number",
            field=models.CharField(
                help_text="Booth Number (e.g. 001, 145A)", max_length=50
            ),
        ),
    ]
