# Generated by Django 6.0.1 on 2026-02-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0010_politicalparty"),
    ]

    operations = [
        migrations.AddField(
            model_name="politicalparty",
            name="accent_gradient",
            field=models.CharField(
                default="linear-gradient(to bottom, #FF9933, #ffffff, #138808)",
                help_text="CSS gradient string",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="politicalparty",
            name="primary_color",
            field=models.CharField(
                default="#000080",
                help_text="Primary Hex Color (e.g. #000080)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="politicalparty",
            name="short_label",
            field=models.CharField(
                blank=True, help_text="e.g. INC, CPIM, BJP", max_length=10
            ),
        ),
    ]
