# Generated by Django 6.0.1 on 2026-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0011_politicalparty_accent_gradient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="politicalparty",
            name="candidate_image",
            field=models.CharField(
                blank=True,
                help_text="Path or filename of the candidate photo",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="politicalparty",
            name="candidate_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
