# Generated by Django 6.0.1 on 2026-02-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0012_politicalparty_candidate_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="politicalparty",
            name="candidate_image",
        ),
        migrations.RemoveField(
            model_name="politicalparty",
            name="candidate_name",
        ),
        migrations.AddField(
            model_name="constituency",
            name="candidate_image",
            field=models.CharField(
                blank=True, help_text="Filename of candidate photo", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="constituency",
            name="candidate_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
