# Generated by Django 6.0.1 on 2026-02-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0013_remove_politicalparty_candidate_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constituency",
            name="candidate_image",
        ),
        migrations.RemoveField(
            model_name="constituency",
            name="candidate_name",
        ),
    ]
