# Generated by Django 6.0.1 on 2026-02-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0014_remove_constituency_candidate_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="voter_leaning",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UDF", "UDF"),
                    ("LDF", "LDF"),
                    ("NDA", "NDA"),
                    ("NEUTRAL", "Neutral"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
