# Generated by Django 6.0.2 on 2026-02-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0015_alter_voter_voter_leaning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERUSER", "Superuser (Global Admin)"),
                    ("MANAGER", "Manager (Global Monitor)"),
                    ("CONSTITUENCY_ADMIN", "Constituency Admin"),
                    ("ZONE_COMMANDER", "Zone Commander"),
                    ("BOOTH_AGENT", "Booth Agent"),
                ],
                default="BOOTH_AGENT",
                max_length=20,
            ),
        ),
    ]
