# Generated by Django 6.0.2 on 2026-02-15 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0016_alter_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded this batch",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_voters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERUSER", "Superuser (Global Admin)"),
                    ("MANAGER", "Manager (Global Monitor)"),
                    ("OPERATOR", "Operator (Data Entry - Own Batches)"),
                    ("CONSTITUENCY_ADMIN", "Constituency Admin"),
                    ("ZONE_COMMANDER", "Zone Commander"),
                    ("BOOTH_AGENT", "Booth Agent"),
                ],
                default="BOOTH_AGENT",
                max_length=20,
            ),
        ),
    ]
