# Generated by Django 6.0.2 on 2026-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0019_messagetemplate_communicationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_edit_voters",
            field=models.BooleanField(
                default=True, help_text="Can update voter intelligence & phone numbers"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_manage_system",
            field=models.BooleanField(
                default=False, help_text="Can add locations & manage parties"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_send_broadcasts",
            field=models.BooleanField(
                default=False, help_text="Can access Communication Hub & send messages"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_upload",
            field=models.BooleanField(
                default=False, help_text="Can access OCR Engine & upload lists"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_verify",
            field=models.BooleanField(
                default=True, help_text="Can approve/save OCR results to DB"
            ),
        ),
    ]
