# Generated by Django 6.0.2 on 2026-02-18 07:58

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0020_userprofile_can_edit_voters_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="voter",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["full_name"],
                name="voter_name_gist_trgm",
                opclasses=["gist_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="voter",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["house_name"],
                name="voter_house_gist_trgm",
                opclasses=["gist_trgm_ops"],
            ),
        ),
    ]
