# Generated by Django 6.0.2 on 2026-02-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0021_voter_voter_name_gist_trgm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "digitized_total",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total voters digitized in this booth so far",
                    ),
                ),
                (
                    "udf_total",
                    models.PositiveIntegerField(
                        default=0, help_text="Total confirmed UDF supporters"
                    ),
                ),
                ("ldf_total", models.PositiveIntegerField(default=0)),
                ("nda_total", models.PositiveIntegerField(default=0)),
                ("neutral_total", models.PositiveIntegerField(default=0)),
                (
                    "new_digitized",
                    models.IntegerField(default=0, help_text="Net new digitized today"),
                ),
                (
                    "new_udf",
                    models.IntegerField(
                        default=0,
                        help_text="Net new UDF converts today (from Neutrals/Others)",
                    ),
                ),
                ("new_ldf", models.IntegerField(default=0)),
                ("new_nda", models.IntegerField(default=0)),
                (
                    "winning_chance",
                    models.FloatField(
                        default=0.0,
                        help_text="Winning probability based on current confirmed + likely trend",
                    ),
                ),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_stats",
                        to="core_db.booth",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Progress Tracking",
                "ordering": ["-date", "booth"],
                "unique_together": {("booth", "date")},
            },
        ),
    ]
