# Generated by Django 6.0.2 on 2026-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0022_dailyprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="head_name",
            field=models.CharField(
                blank=True,
                help_text="Primary contact person for this booth",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booth",
            name="head_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="localbody",
            name="head_name",
            field=models.CharField(
                blank=True,
                help_text="Official in charge of this Local Body",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="localbody",
            name="head_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
