# Generated by Django 6.0.1 on 2026-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_db",
            "0023_booth_head_name_booth_head_phone_localbody_head_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booth",
            name="name",
        ),
        migrations.AlterField(
            model_name="booth",
            name="polling_station_name",
            field=models.CharField(
                blank=True,
                help_text="Physical location of the polling station",
                max_length=1000,
            ),
        ),
    ]
