# Generated by Django 6.0.1 on 2026-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0024_remove_booth_name_alter_booth_polling_station_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="full_name",
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="voter",
            name="house_name",
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="voter",
            name="relation_name",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="voter",
            name="source_file",
            field=models.CharField(help_text="Original PDF Filename", max_length=1000),
        ),
    ]
