# Generated by Django 6.0.2 on 2026-03-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0025_alter_voter_full_name_alter_voter_house_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="has_voted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="voter",
            name="voted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
