# Generated by Django 6.0.2 on 2026-03-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0026_voter_has_voted_voter_voted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="is_head_of_family",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
