# Generated by Django 6.0.1 on 2026-03-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0027_voter_is_head_of_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Common name for display",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
