# Generated by Django 6.0.1 on 2026-03-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0028_rename_head_name_booth_booth_agent_name_and_more"),
        ("core_db", "0028_userprofile_full_name_userprofile_phone_number"),
    ]

    operations = []
