# Generated by Django 6.0.1 on 2026-03-21 19:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0029_merge_20260319_1509"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone",
        ),
        migrations.AlterField(
            model_name="dailyprogress",
            name="winning_chance",
            field=models.FloatField(
                default=0.0,
                help_text="Winning probability (0.0-1.0) based on current confirmed + likely trend",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(150),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="phone_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10,15}$", "Phone number must be 10-15 digits"
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="voter",
            index=models.Index(
                fields=["booth", "serial_no"], name="voter_booth_serial_idx"
            ),
        ),
    ]
