# Generated by Django 6.0.3 on 2026-03-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0030_remove_userprofile_phone_voter_is_digitized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="is_digitized",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
