# Generated by Django 6.0.3 on 2026-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0031_add_voter_is_digitized"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="family_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
