# Generated by Django 6.0.3 on 2026-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0032_add_voter_family_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="constituency",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to block all services for this constituency",
            ),
        ),
    ]
